### ISSUE TITLE
객체들의 협력 다이어그램으로 시각화해보기

### ISSUE THREAD

**Issue by hi-hyein** [hi-hyein/starCraftUnitOOP#1]
- [x] 10:00 ~ 11:00

문서로만 작성된 객체들의 협력 
다이어그램으로 표현해보기
+ 다이어그램으로 표현해보며 문서화에서 빠졌던 부분 체크해보기

**Comment by hi-hyein** [comment]
[ ] 17:00 ~ 18:00

- UML 클래스 다이어그램 이론 정리
- 이전 다이어그램 스케치 다듬고 관계 표현 발전 시켜보기

**Comment by hi-hyein** [comment]
- [ ] 10:00 ~ 11:00
- 1. Commander가 마우스의 입력을 받아 유닛을 이동시킨다는 것을 고려하여  유닛 이동 명령을 세분하기
- 2. 유닛이 이동 방식을 좀 더 구체화시키기
- 3. class_diagram02.png의 class diagram 설명 추가하기

**Comment by hi-hyein** [comment]
[Unity에서 2d캐릭터가 이동하는 방법을 찾아보기](https://www.notion.so/70eb10e0964c4917be89975bb8acd05f)

**Comment by hi-hyein** [comment]
- [ ] 12:00 ~ 1:00
step02.md 클래스다이어그램 commander 설명 업데이트하기

**Comment by hi-hyein** [comment]
일정으로 인해서 오늘 계획 진행이 어려워 
4/11일 일요일 2시간으로 진행하겠습니다!

- [ ] 9:00 ~ 11:00

1. enum type으로 저그 unit 구조 변경
2. 내 유닛 리스트의 드론, 라바 목록 하나로 관리할 수 있도록 구조 변경
3. 변경된 내용 문서, 다이어그램 업데이트

**Comment by hi-hyein** [comment]
4월 17일 계획 진행이 어려워 4월 18일 2시간으로 진행

- [ ] 10:00 ~ 12:00

**Comment by hi-hyein** [comment]
# 오늘의 삽질(?)기록 
```
using System;
using System.Collections.Generic;

public enum CommanderList {
	zerge,
	terran,
	protoss
}

public enum ZergUnits {
	labar,
	drone
}

public class Unit {
	public enum name;
	public vector3 position = new vector3(0,0,0);
}

public class labar : Unit {
}

public class MyUnit {
	public List<Unit> MyUnitList = new List<Unit>();
}

public class Commander {
	public CommanderList Name;
	public MyUnit myUnit;
	
    // 임시 초기화
    public void init(CommanderList _Name){
		Name = _Name;
   }
	
	// 유닛 생성 
	public void createUnit(){
	}
}


public class main {
	public static void Main() {
		// 저그 생성
		Commander zerge = new Commander();
		// 저그 초기화(임시)
		zerge.init(CommanderList.zerge);
		// 저그 유닛 생성
		zerge.createUnit(ZergUnits.labar);
	}
}
```
- step02에 작성한 내용이 매끄럽게 잘 이어지는지 확인해보고 싶어서
임시 코드들로 테스트 해봄 (위 코드는 테스트를 위해서 지웠다, 작성했다를 반복한 코드)

## 문제점1
- 임시로 코드를 만들어 작성하면서 매끄럽게 작성되지 않아서 내가 만들었지만 정리가 잘 안되어있는 것 같음
- 작성한 부분들을 작은 단위로? 다시 매끄럽게 이어질 수 있는지 체크해보기
## 문제점2
-  상속과 인스턴스생성의 구분을 제대로 하지 않고 문서를 작성한 것 같은 느낌이 들었음
- 저그를 인스턴스로 만들어야하나, 상속을 해서 클래스로 구현해야하나
- 라바,드론같은 유닛을 인스턴스로 만들어야하나, 상속을 해서 클래스로 구현해야하나
- 이 문제에 대해 정리해보기

**Comment by jongfeel** [comment]
우선 compile error부터 잡고 시작해야 겠는데요??
- 웹만 하셔서 생소할 수 있는데 실행하기 전에 문법 오류를 잡아준다고 생각하시면 좋습니다.

그리고 실제 코드를 작성하시면 pull reqeust를 주시면 어떨까 싶습니다.

저한테 assignee를 주신게 아니라서 간단한 코멘트만 남겨 봅니다.

**Comment by hi-hyein** [comment]
@jongfeel 
네! 맞아요..compile error가 나서 일단 기록먼저 해두고 마무리지었는데요!
compile error잡고 정리해서 pr드리겠습니다! 
신경써서 봐주셔서 감사합니다 👯 👯 👯 👯 👯

**Comment by hi-hyein** [comment]
step02 문서 불필요한 부분 제거, class diagram 업데이트
- [ ] 22:00 ~ 23:00 중 30분 (나머지 30분은 다음이슈에서..)
