### ISSUE TITLE
2nd meeting, 2021-05-27

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/starCraftUnitOOP#11]
#6 

pull request review
답변은 다 해드렸는데 추가적으로 merge가 진행되지 않음

#7 #9 

github actions 사용, 테스트 코드 자동화 진행
잘 안되고 있는 부분 리뷰 필요

**Comment by hi-hyein** [comment]
@jongfeel 

5월 27일 목요일로 일정 변경부탁드립니다.
멘토님 다시 한 번 죄송합니다.
이런 어처구니 없는 실수를 해서 너무 부끄럽네요..

**Comment by jongfeel** [comment]
제 생각에도 일정을 깜빡 하신 것 같더라고요.
일부러 그런거 아니면 괜찮습니다.

그러면 미팅 일정은 5월 27일로 변경할께요.

**Comment by jongfeel** [comment]
#12 이 부분을 진행하는 걸 목표로 했으면 합니다.
