### ISSUE TITLE
작은 단위의 분석 설계, 그리고 TDD

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/starCraftUnitOOP#12]
최소로 하나의 동작을 보장하는 요구사항을 잘 정리해 보시고
그걸 바탕으로 분석한 내용을 적은 후에
설계를 진행하시고 (class랑 method 코드 정도 포함한)

이렇게 만들어진 설계 코드를 바탕으로 테스트 코드를 작성하는 것 까지를 한번 해보셨으면 합니다. (a.k.a TDD)
=> 무엇을 테스트할 것인가? 분석한 내용을 바탕으로 나오면 됩니다.

**Comment by hi-hyein** [comment]
주말 일이있어 진행가능한만큼만(깃헙액션 유니티라이센스 업데이트)진행하였습니다.
주말 할당량은 금주 평일에 진행할 예정입니다~

**Comment by hi-hyein** [comment]
@jongfeel 
멘토님 커맨더 -> 유닛 선택하기의 요구사항을 조금 더 추가해보았는데요 
어떻게 선택하고, 해제해야되는지를 구체적으로 생각해보았어요~
그런데 선택을 해제하는 경우에는 다른 메서드로 분리가 되어야 할까요?

**Comment by jongfeel** [comment]
method를 분리하는게 더 명확할겁니다.

그러면 요 유닛 선택하기의 작은 범위로 분석 설계 부터 진행하실 건가요?

**Comment by hi-hyein** [comment]
> method를 분리하는게 더 명확할겁니다.
> 
> 
> 
> 그러면 요 유닛 선택하기의 작은 범위로 분석 설계 부터 진행하실 건가요?

오 감사합니다
넵 유닛선택하기부터 진행할거에요!

**Comment by jongfeel** [comment]
생각난걸 말씀 드리면 

1.
유닛 선택이란 걸 꼭 마우스나 키보드로 해야 한다는 생각은 안하셔도 됩니다.
실제 게임 했을 때의 그 인터페이스를 생각하면 테스트 코드 만드는데 엄청 힘들거거든요.

2.
Use case 역시 한번 뽑아보면 좋을 것 같은데
test 코드 짜는데 도움이 좀 될 수 있어서 그렇습니다.

3.
설계 진행하시면 객체의 역할, 책임, 협력이 어떻게 진행될지 한번 생각해 보시고, 그림도 그려보신 후에 코드를 짜보시면 좋을 것 같습니다.
꼭 어떤 형식과 규칙에 맞춰서 그려야 하는 부담감은 덜어내시고, 생각하신 대로 해보셨으면 좋겠습니다.

**Comment by hi-hyein** [comment]
- [x] 24:00 ~ 02:00
- SelectUnit 테스트코드 추가
-  SelectUnit 구현

**Comment by hi-hyein** [comment]
@jongfeel 
멘토님 pr관련 질문인데요~! 
pr을 단계별로 보내고싶어서 (예를 들어 1. 분석단계 pr, 2. 테스트코드 pr)
분석 브랜치, 테스트 코드 브랜치(분석 브랜치 기반)로 따로 나눴는데
해보니...단계별로 pr은 보내지는데 2번 테스트코드 pr같은경우는 분석브랜치기반으로 생성된거라 
분석브랜치 커밋들도  같이 들어가다보니 단계를 나누는 의미가 없는 것 같더라구요..ㅠㅠ
혹시 좋은 pr방법이 없을까요ㅋㅋ..

**Comment by jongfeel** [comment]
master <- analysis
master <- unittest

요렇게 master에서 branch를 만들어서 하면 괜찮을 수 있어요.

**Comment by hi-hyein** [comment]
- [x] 20:00 ~ 22:00
- Selected method 변경
- myUnits Commander class로 이동
- 유닛 얻는 mehthod 추가
- 유닛 선택하기 테스트 코드 업데이트

**Comment by jongfeel** [comment]
main -> analysis
analysis -> test

main <- analysis, pull request
main <- test, pull request
