### ISSUE TITLE
프로젝트 중단 및 회고

### ISSUE THREAD

**Issue by jongfeel** [hi-hyein/starCraftUnitOOP#19]
개인 사정으로 시간을 낼 수 없어 프로젝트를 중단 요청을 했습니다.
기간으로는 3월 6일 부터 7월 5일 까지의 긴 시간이었지만 미팅은 3회 진행 했네요.

회고를 남길 수 있다면 여기에 코멘트로 남겨 보면 좋을 것 같아요.
마지막이니 기한은 혜인님이 정해 주시고 코멘트 달아 주시면 좋을 것 같습니다.
저도 그 기한에 맞춰 코멘트 달겠습니다.

**Comment by hi-hyein** [comment]
@jongfeel 
넵
7월 18일까지 회고를 남겨보겠습니다!

**Comment by hi-hyein** [comment]
# 회고

객체지향의 사실과 오해를 읽은 후 멘토님과 북토크를 진행하며 본격적으로 객체지향에 대한 관심이 생겼다.

그리고 우연히 객체지향의 특징이 스타크래프트의 유닛과 비슷하다는 것을 생각해내면서 좀 더 깊은 이해를 해 보고자 스타크래프트의 유닛을 객체지향으로 만들어 보자! 마음먹고 이 프로젝트를 진행하게 되었다.

다른 일정들 사이에 프로젝트를 진행하고 싶어서 스타크래프트 유닛 프로젝트는 주말 두 시간씩 4주를 진행하고 멘토링을 받는 방식으로 진행되었다.

일주일에 두 시간씩 진행해본 결과 일정에 대한 부담감은 줄었지만 뭔가를 하기엔 짧은 시간이라는 생각이 들었다. 이 짧은 시간을 잘 쓰기 위해서는 미리 무엇을 할 것인지 작은 단위로 계획을 해두고 사전 준비를 조금 해놓은 상태에서 진행해야 했다. 이렇게 미리 생각해둔 상태에서 짧은 시간을 진행했을 때 더 효율적으로 사용했던 것 같다. 하지만 매번 이렇게 진행하지 못하고 두 시간을 채우는 방식으로 진행할 때가 더 많아서 아쉬웠다.

Javascript가 아닌 C#과 Unity로 프로젝트를 진행하며 javascript로 프로젝트를 진행할 때와는 많이 다른 환경에 적응이 조금 필요했지만 새로운 언어로 프로젝트를 진행하며 다른 동네를 경험해본다는 것이 정말 중요하다는 생각이 들었다.

이 프로젝트를 진행하며 객체지향을 알게 된 것은 아니다. 기간도 짧았고, 이 짧은 기간 동안 객체지향을 알았다고 한다면 거짓말일 것이다. 다만 어떤 객체를 만들기 위해서는 설계가 가장 중요하다는 것을 아주 잘 알게 되었다. 코드를 작성할 때 막히거나, 테스트 코드를 짜야 하는데 뭘 짜야 하는지 모르는 이유는 설계가 부족하기 때문이란 것을 프로젝트를 진행하며 알게 되었기 때문이다.

만약 이 프로젝트를 진행하지 않았다면, 설계가 중요하다고는 하지만 정말 왜 중요한지에 대해서는 알지 못했을 것이다. 그리고 무작정 코드를 작성하고 싶어 했을 것이다.

그리고 정말 작은 단위로 설계를 하는 것이 중요하단 것도 알았다.

나름 작은 단위로 설계를 진행하고 있다고 생각했는데 그렇지 않아서 설계가 복잡해지고, 복잡한 설계로 인해서 내가 무엇을 설계했는지 파악이 어려운 순간도 있었다. 그런데 정말 최소한의 단위로 진행하니 생각이 정리가 되기 시작했다.

짧은 기간이었지만 책과, 설명으로만 들었던 부분에 대해서 직접 느껴볼 수 있는 기회가 되었다.
아직도 객체지향과 설계는 어렵지만 마냥 뜬구름 같은 이야기로 남지 않게 되어서 다행이라고 생각한다.

**Comment by jongfeel** [comment]
## 회고

### 잘 진행된 부분

- 객체지향 프로그래밍의 연습으로 할만한 주제에 대해 스타크래프트 게임을 생각한 부분, 연습을 위한 연습이 아닌 해보면 재미있는 부분을 잘 잡아서 진행
- 아주 큰 범위를 잡지 않고 유닛 생성 및 이동에 대한 테스트 정도만 하는 범위를 잡아서 했다는 점 => 시간이 지나면서 쳐지지 않고 짧은 기간에 할 수 있는 범위로는 매우 적합
- 설계 하는 부분에 있어서 객체 간의 인터페이스, 즉 메서드에 대한 이해를 리뷰를 통해 진행 => 객체지향의 사실과 오해라는 책에서 언급된 걸 실제로 생각해 보면서 구현한 부분이 크게 의미가 있었다고 생각함
- Unit test를 하는 과정에서 TDD 까지는 아니지만 무엇을 테스트 해야 하는지에 대한 이해, 그리고 그 코드를 짤 수 있었다는 부분에서 좋은 의미라고 보고 싶음.

### 아쉬운 부분

- 앞으로 4주 단위의 멘토링은 최대한 안하는게 좋다는 걸 느낌 => 2주 까지는 좋은데, 3주 4주는 너무 늘어지는 부분이 있고 생각보다 진도가 잘 나가지 않는 다는 점
- 정말 짧게 끊어서 완료할 수 있다고 생각한 범위도, 다 구현하지 못했다는 점 => 조금 더 관심을 가지고 컨트롤 해야 할 부분이라고 느꼈으며 역으로 pull request를 주는 것도 어땠을까 하는 생각도 듬

**Comment by jongfeel** [comment]
@hi-hyein 

짧기도 했고 완료도 하지는 못했지만 그래도 책에 있는 내용 - 실제 구현하면서 얻는 부분이 있었다는 점에서 아주 좋은 것 같습니다. 혹시 저한테 아쉬운 점도 있으시면 얘기해주셔도 좋습니다.
